### ISSUE TITLE
General - Footer media name and URL 中文和ENG 要不一样

### ISSUE THREAD

**Issue by herberttse** [JemexIdeas/JemexEvent#201]
英文

> LinkedIn
> Twitter
> Facebook
> Google+
> 
> https://www.linkedin.com/company/mobile-world-congress-shanghai
> https://twitter.com/gsma
> https://www.facebook.com/mwcshanghai/
> https://plus.google.com/communities/109107046916957618119

![snip20160201_103](https://cloud.githubusercontent.com/assets/16773800/12716255/f72dbeb6-c919-11e5-97c4-d316c5697e86.png)

**Comment by riseno** [comment]
have been resolved.

**Comment by Crystaltsn** [comment]
Login account入去做upgrade的，英文版的footer變咗咁樣
![image](https://cloud.githubusercontent.com/assets/16987335/12784059/2a0a8cda-ca85-11e5-8de9-69763a35e261.png)
@riseno

**Comment by herberttse** [comment]
@riseno @Crystaltsn 
Retest today: 0204g@mail.com
Upgrade pass button, redirect to this page , footer seems alright
Upgrade with code,  redirect to this page , footer seems alright
close it for now

**Comment by Crystaltsn** [comment]
@herberttse @riseno 

English version 
create account page footer still wrong

![image](https://cloud.githubusercontent.com/assets/16987335/12809222/9b7f8530-cb1d-11e5-8a22-edfe7024bb30.png)

**Comment by herberttse** [comment]
@riseno @Crystaltsn 
not the cashed problem, different browser showing differently.

![snip20160204_18](https://cloud.githubusercontent.com/assets/16773800/12809395/9c712066-cb59-11e5-83f7-65a3711521ea.png)
